
var async = require ('async');
var filth = require ('filth');
var likeness = require ('likeness');

/**     @class substation.Action
    @root
    Wraps a reaction function with its html templates, input schemata, minimum authentication
    requirements and other minor configuration options to create a multi-transport handler.
@argument/.Configuration config
    @optional
    Specify templates, input schemata, minimum authentication requirements, and other options.
@callback/Function reaction
    The reaction function, i.e. the working business logic being served by `substation` at a given
    url-matching expression and request method.

    @argument/Array[String] params
        Selecting groups in the url, filled by the request url provided by the user.
    @argument/substation.AuthenticationStatus auth
        Specifies the current authentication level of the user accessing this Action.
    @argument/Reply reply
*/
function Action (config, reaction) {
    this.config = filth.clone (DEFAULT_CONFIG);
    filth.merge (this.config, config);
    this.reaction = reaction;
}


/**     @member/Function configure
    Adjust the [configuration](.Configuration).
*/
Action.prototype.configure = function (config) {
    filth.merge (this.config, config);
};



/**     @class Configuration
@member/String|RegExp|undefined route
    As an alternative to setting the route [when activating the Action](substation#addAction) you
    may set it in the configuration. Routes specified in `addAction` override configured routes.

    When a route is set as a String, it is prepended with a forward slash if none is present and
    converted to a regular expression of the form `/pathname(?:/(.*))?`.
@member/Object|Function|undefined template
    Define one or more template Functions to convert a context Object to an html string. If a
    Function is used, all html responses are generated by this Function. If an Object is provided,
    http response codes are mapped to templates. If a response code cannot be matched exactly, it
    falls back to the `200` template, then attemps an exact match and finally the `200` template on
    the [global templates](substation.Configuration#template).

    Template Functions may be synchronous or asynchronous. The context Object and a callback
    Function are passed as arguments.
@member/Object|undefined context
    When generating html with a template but never when generating a JSON response, [response
    content](substation.Response#content) is non-destructively deep-merged over this Object. To put
    it another way, `context` sets default content for html pages.
@member/Function|undefined setup
    Called during the parent server's initialization stage, before the server has begun accepting
    requests. It's usually the best time to establish database access. Two arguments are passed:
     * [Object]() `configuration` The Action's configuration Object. You may still edit the
        configuration at this point.
     * [Function]() `callback` Call when the Action is ready to use.
@member/JSON authentication
    @property/Boolean Authentication.isLoggedIn
        @default `false`
        Require that the Agent be logged into the application to use access this Action.
    @property/Boolean Authentication.isDomestic
        @default `false`
        Require that the Agent have same-origin access priveleges in the client context to use this
        Action. This secures against XSS attacks in the browser.
    @property/Boolean Authentication.allowGuests
        @default `true`
        Requires that an Agent be at least an Idle Agent to use this Action. An Idle Agent is one
        that presents an expired session token. It is possible for an Idle Agent to be Domestic.
@member/Object bodySchema
    A JSON Schema document used to restrict request body content. filth form requests are mapped
    to simple flat Objects and JSON bodies are validated as-are. Failure to validate will cause a
    `406` response to be automatically sent. When `bodySchema` is present, an Action's
    `request.body` can always be assumed to conform. Finally, the parent server will automatically
    respond to OPTIONS requests with `{ VERB:{ body:bodySchema, query:querySchema }, ...`.

    Schemata are pre-compiled with [likeness](https://github.com/shenanigans/node-likeness) for
    rapid validation. This allows `$ref` to validate much more quickly, however, it will load
    references when the server starts and does not keep them up to date (yet).
@member/Object querySchema
    A JSON Schema document used to restrict request url query terms. The query is mapped as a simple
    flat Object and the field `_domestic` is automatically stripped before validation. Failure to
    validate will cause a `406` response to be automatically sent. When `querySchema` is present, an
    Action's `request.query` can always be assumed to conform. The parent server will automatically
    respond to OPTIONS requests with `{ VERB:{ body:bodySchema, query:querySchema }, ...`.

    Schemata are pre-compiled with [likeness](https://github.com/shenanigans/node-likeness) for
    rapid validation. This allows `$ref` to validate much more quickly, however, it will load
    references when the server starts and does not keep them up to date (yet).
*/


/**     @class Request
    Incoming Action requests, whether from `http` or `Socket.io` are mapped to a Request instance.
    If [bodySchema](.Configuration#bodySchema) and/or [querySchema](.Configuration#querySchema) are
    set, the `body` and/or `query` properties can be assumed to be conformant by the time the
    reaction Function is called.
@member/String method
    The method used to access this Action. Used when the Action is [mounted](substation#addAction)
    without a method specified.
@member/Object query
    Request url terms, GET parameters, etc. mapped as a simple flat Object and validated by the
    [query schema](.Configuration#querySchema) if specified.
@member/Array params
    If the route regex selected text after the route pattern or the route regex contains matching
    groups, the additional matched strings are passed in an Array.
@member/Object|streams.ReadableStream|undefined body
    The request body. Form requests are mapped to a simple flat Object and validated by the
    [body schema](.Configuration#bodySchema) if specified. JSON bodies are parsed and validated. If
    the [binary streams option](.Configuration#binaryStreams) is set, the body may be a [readable
    stream](streams.ReadableStream). These actions should type-check with `instanceof` and dispatch
    accordingly, or use the [never buffer option](.Configuration#neverBuffer).
@member/Array|undefined files
    When [cacheFiles](.Configuration#cacheFiles) is set, an Array of file info Objects containing
    Buffers is passed. This is part of an unstable feature.
@member/stream.Readable|undefined stream
    When [binaryStreams](.Configuration#binaryStreams) is set, content types other than lightweight
    forms and JSON will be streamed instead of cached. If you do not consume the body before
    [replying](substation.Reply#done) the incoming body stream is automatically closed with the
    'Connection:close' header.
@member/String|undefined contentType
    If the remote client has provided it, the value of the `Content-Type` header is included
    whenever `stream` is used.
*/


/**     @member/Function run
    Try to perform this [Action](substation.Action) as a given Agent using a particular [Request]
    (.Request) and wrap the result in a [Reply.](.Reply). Subject to immediate failure conditions
    if the [body](.Configuration#bodySchema) or [query](.Configuration#querySchema) fail schema
    validation, if the agent is not [sufficiently authenticated](.Configuration#authentication),
    if the body's content-type is [not acceptable](.Configuration#binaryStreams), or if the reaction
    Function synchronously throws an [Error](). Error conditions are routed through the templates
    by the http codes `403` and `406`.
@argument/substation station
    The [substation]() instance managing this request.
@argument/substation.Agent agent
    Authentication manager for the requesting user and their device. Used to view or change the
    User's login status.
@argument/.Request request
    Details of the request. The `request` Object is consistent across network transports to help
    similar requests be holistically similar.
@argument/substation.Action.Reply reply
    Return a JSON body document associated with the request, automatically rendered by templates
    when required, and/or emit events on the client device that are not associated with the request
    in any way. Events emitted by a `reply` are not distinct from those produced by
    [station.sendEvent](substation#sendEvent).
*/
Action.prototype.run = function (station, agent, request, reply) {
    if (this.querySchema) try {
        this.querySchema.validate (request.query);
    } catch (err) {
        console.log ('query error');
        reply.content ({ SchemaError:err });
        return reply.done (400);
    }

    if (this.bodySchema) try {
        this.bodySchema.validate (request.body);
    } catch (err) {
        console.log ('body error');
        reply.content ({ SchemaError:err });
        return reply.done (400);
    }

    try {
        this.reaction (station, agent, request, reply);
    } catch (err) {
        console.log (err.stack);
        station.logger.error ({ error:err, action:this.name }, 'action error');
        reply.content ({ ActionError:err });
        reply.done (400);
    }
};


/**     @member/Function toHTML

@argument/submergence:Reply reply
*/
Action.prototype.toHTML = function (station, status, context, callback) {
    var template;
    var selectedStatus = status;
    if (this.template && (
        Object.hasOwnProperty.call (
            this.template,
            selectedStatus
        )
     || Object.hasOwnProperty.call (
            this.template,
            selectedStatus = '200'
        )
    ) )
        template = this.template[selectedStatus];
    else if (this.globalTemplates && (
        Object.hasOwnProperty.call (
            this.globalTemplates,
            selectedStatus = status
        )
     || Object.hasOwnProperty.call (
            this.globalTemplates,
            selectedStatus = '200'
        )
    ) )
        template = this.globalTemplates[selectedStatus];

    if (!template)
        return
            "<!DOCTYPE html>\n<body>\n"
          + JSON.stringify (context)
          + "\n</body>\n</html>"
          ;

    try {
        var done = false;
        var self = this;
        var html = template (context, function (err, html) {
            if (done) {
                station.logger.error ({
                    action:     self.name || self.pattern.toString.slice (1, -1),
                    status:     status,
                    error:      "template provided asynchronous html after synchronous html"
                });
                return;
            }

            if (err) {
                station.logger.error ({
                    err:        err,
                    action:     self.name || self.pattern.toString.slice (1, -1),
                    status:     status,
                    error:      "template provided asynchronous error after synchronous html"
                });
                return callback (err);
            }

            callback (undefined, html);
        });
        if (html) {
            done = true;
            callback (undefined, html);
        }
    } catch (err) {
        station.logger.error ({
            err:        err,
            action:     self.name || self.pattern.toString.slice (1, -1),
            status:     status,
            error:      "template threw an Error"
        });
        return callback (err);
    }
};


/**     @struct Configuration
    Configuration options for [Actions](.).
@member/JSON authentication
    Specify a minimum authentication profile to access this Action. Unauthenticated requests are
    automatically served a blank 403 response.

    @property authentication.loggedIn
    @property authentication.domestic
@member/Function|Object template
    When a client uses this Action over the REST transport, a template will be executed if it is
    supplied. Specify either a single template Function or a map of response codes to template
    Functions. Wildcards may be used i.e. "2xx" or "30x". Most specific response code wins.

    @argument/Object template(context
        The template's execution context, i.e. the document to render to html.
    @callback template(callback
        @optional
        If the template does not return a String, `substation` will wait for this callback.
        @argument/Error|undefined err
        @argument/String html
            Rendered html output.
        @returns
    @returns/String|undefined template)html
        Synchronous templates may return their rendered content immediately and ignore the callback.
@member/Boolean binaryStreams
    @default `false`
    If true, accept unknown content types and pass them, as well as `multipart/form-data` requests,
    to the Action as streams. The passed `request.body` will be a `ReadableStream` instance.
@member/Boolean neverBuffer
    @default `false`
    When [binaryStreams](#binaryStreams) is set and so is `neverBuffer`, the [request body]
    (.Request.body) is always a [stream](streams.ReadableStream).
@member/Number bufferFiles
    @default `64000`
    Prebuffer trivial files into memory, up to the given number of bytes across all uploaded files.
    Handy for handling small file uploads (such as user avatars) in an application where file
    uploads are not a significant feature.
@member/
*/
var DEFAULT_CONFIG = {
    binaryStreams:  false,
    neverBuffer:    false,
    bufferFiles:    64000,
    maxBodyLength:  40960
};


/**     @member/Function setup
    Perform any asynchronous setup tasks necessary to prepare this Action to react to requests. Runs
    any configured [setup](.Configuration#setup) function. Schema are submitted to `likeness` at
    this point and compiled when [ready](#ready) is called.
@callback
*/
Action.prototype.setup = function (station, schemaContext, callback) {
    var self = this;

    if (this.config.setup)
        return this.config.setup (station, this.config, function (err) {
            if (self.config.template)
                if (typeof self.config.template == 'function')
                    self.template = { 200:self.config.template };
                else
                    self.template = self.config.template;

            async.parallel ([
                function (callback) {
                    if (!self.config.bodySchema)
                        return callback();
                    self.bodySchemaExport = self.config.bodySchema;
                    schemaContext.submit (self.config.bodySchema, callback);
                },
                function (callback) {
                    if (!self.config.querySchema)
                        return callback();
                    self.querySchemaExport = self.config.querySchema;
                    schemaContext.submit (self.config.querySchema, callback);
                }
            ], callback);
        });

    if (this.config.template)
        if (typeof this.config.template == 'function')
            this.template = { 200:this.config.template };
        else
            this.template = this.config.template;

    async.parallel ([
        function (callback) {
            if (self.config.bodySchema)
                schemaContext.submit (self.config.bodySchema, callback);
            else
                callback();
        },
        function (callback) {
            if (self.config.querySchema)
                schemaContext.submit (self.config.querySchema, callback);
            else
                callback();
        }
    ], callback);
};


/**     @member/Function ready

*/
Action.prototype.ready = function (schemaContext, callback) {
    var self = this;
    async.parallel ([
        function (callback) {
            if (!self.config.bodySchema)
                return callback();
            self.originalBodySchema = self.config.bodySchema;
            schemaContext.compile (self.config.bodySchema, function (err, compiled, metaschema) {
                if (err) return callback (err);
                self.compiledBodySchema = compiled;
                likeness.helpers.fromJSONSchema (metaschema, compiled, function (err, likeDoc) {
                    if (err) return callback (err);
                    var schema;
                    try {
                        schema = new likeness (likeDoc);
                        self.bodySchema = schema;
                    } catch (err) {
                        return callback (err);
                    }
                    callback();
                });
            });
        },
        function (callback) {
            if (!self.config.querySchema)
                return callback();
            self.originalQuerySchema = self.config.querySchema;
            schemaContext.compile (self.config.querySchema, function (err, compiled, metaschema) {
                if (err) return callback (err);
                self.compiledQuerySchema = compiled;
                likeness.helpers.fromJSONSchema (metaschema, compiled, function (err, likeDoc) {
                    if (err) return callback (err);
                    var schema;
                    try {
                        schema = new likeness (likeDoc);
                        self.querySchema = schema;
                        return callback();
                    } catch (err) {
                        return callback (err);
                    }
                });
            });
        }
    ], callback);
};

/**     @member/Function export

*/
Action.prototype.export = function(){
    var output = { name:this.name };
    if (this.route)
        output.route = this.route.toString().slice (1, -1);
    if (this.method)
        output.method = this.method;
    if (this.config.Authentication)
        output.Authentication = filth.clone (this.config.Authentication);
    if (this.config.querySchema)
        output.querySchema = this.compiledQuerySchema;
    if (this.config.bodySchema)
        output.bodySchema = this.compiledBodySchema;
    return output;
};


module.exports = Action;
